tabuada = int(input("Digite um número para ver a sua tabuada"))

print("{} x 01 = {}".format(tabuada, tabuada * 1))
print("{} x 02 = {}".format(tabuada, tabuada * 2))
print("{} x0 3 = {}".format(tabuada, tabuada * 3))
print("{} x 04 = {}".format(tabuada, tabuada * 4))
print("{} x0 5 = {}".format(tabuada, tabuada * 5))
print("{} x 06 = {}".format(tabuada, tabuada * 6))
print("{} x 07 = {}".format(tabuada, tabuada * 7))
print("{} x 08 = {}".format(tabuada, tabuada * 8))
print("{} x 09 = {}".format(tabuada, tabuada * 9))
print("{} x 10 = {}".format(tabuada, tabuada * 10))
